Repository thoth-station/build-watcher, pull requests merged in 2019-04, with the labels that each got.

#23 fixed the webhook url of the build trigger job
  .zuul.yaml
Labels: approved

#21 Use versions of libraries from PyPI
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#24 Automatic update of dependency thoth-common from 0.8.3 to 0.8.5
  Pipfile.lock
Labels: bot

#25 Added a required field for deployment of dc and imagestream in differ…
  openshift/deployment-template.yaml
  playbooks/build-watcher/tasks/main.yaml
  playbooks/provision.yaml
Labels: approved, size/XS
