Repository thoth-station/build-watcher, pull requests merged in 2019-09, with the labels that each got.

#61 Distinguish TLS verification flag
  app.py
  openshift/deployment-template.yaml
Labels: approved, size/M, size/S

#58 Start using Thoth's base image
  .s2i/bin/assemble
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#63 Propagate deployment name for sentry environment
  openshift/deployment-template.yaml
Labels: approved, size/XS

#64 Automatic update of dependency thoth-common from 0.9.8 to 0.9.9
  Pipfile.lock
Labels: bot

#65 Automatic update of dependency thoth-common from 0.9.9 to 0.9.10
  Pipfile.lock
Labels: bot

#66 Automatic update of dependency thoth-analyzer from 0.1.2 to 0.1.3
  Pipfile.lock
Labels: bot

#67 Automatic update of dependency thoth-analyzer from 0.1.3 to 0.1.4
  Pipfile.lock
Labels: bot
