Repository thoth-station/build-watcher, pull requests merged in 2019-07, with the labels that each got.

#43 Automatic update of dependency thamos from 0.5.3 to 0.5.4
  Pipfile.lock
Labels: bot

#45 Automatic update of dependency thoth-common from 0.9.1 to 0.9.2
  Pipfile.lock
Labels: bot

#46 Automatic update of dependency thoth-common from 0.9.2 to 0.9.3
  Pipfile.lock
Labels: bot

#49 Automatic update of dependency thamos from 0.5.4 to 0.5.5
  Pipfile.lock
Labels: bot

#50 Automatic update of dependency thoth-common from 0.9.3 to 0.9.4
  Pipfile.lock
Labels: bot

#51 Prometheus metrics integration for build-watcher
  .gitignore
  app.py
  openshift/deployment-template.yaml
  pyproject.toml
Labels: approved, size/L

#52 update few fixes and also prometheus metrics set operation
  Pipfile
  app.py
Labels: approved, size/M
