Repository thoth-station/build-watcher, pull requests merged in 2019-12, with the labels that each got.

#82 Automatic update of dependency pyyaml from 5.1.2 to 5.2
  Pipfile.lock
Labels: bot, size/S

#83 Automatic update of dependency thamos from 0.7.4 to 0.7.5
  Pipfile.lock
Labels: bot, size/XS

#84 Automatic update of dependency thoth-common from 0.9.19 to 0.9.20
  Pipfile.lock
Labels: bot, size/XS

#85 Automatic update of dependency thamos from 0.7.5 to 0.7.6
  Pipfile.lock
Labels: bot, size/XS

#86 Automatic update of dependency thoth-common from 0.9.20 to 0.9.21
  Pipfile.lock
Labels: bot, size/XS

#87 Automatic update of dependency thoth-analyzer from 0.1.5 to 0.1.6
  Pipfile.lock
Labels: bot, size/S

#88 Update Thoth configuration file and Thoth's s2i configuration
  .thoth.yaml
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#89 Automatic update of dependency thoth-analyzer from 0.1.6 to 0.1.7
  Pipfile.lock
Labels: bot, size/S

#90 Automatic update of dependency thamos from 0.7.6 to 0.7.7
  Pipfile.lock
Labels: bot, size/S

#91 Automatic update of dependency thoth-common from 0.9.21 to 0.9.22
  Pipfile.lock
Labels: bot, size/XS
