Repository thoth-station/build-watcher, pull requests merged in 2019-08, with the labels that each got.

#53 Start using Thoth in OpenShift's s2i
  .s2i/bin/assemble
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: size/M, size/S

#54 Stop using extras in thoth-common
  Pipfile
  Pipfile.lock
Labels: size/L

#55 Initial dependency lock
  Pipfile.lock
Labels: bot, size/L

#57 Automatic update of dependency thoth-common from 0.9.7 to 0.9.8
  Pipfile.lock
Labels: bot

#56 Added config
  .thoth.yaml
Labels: approved, size/S

#60 Automatic update of dependency thamos from 0.7.0 to 0.7.2
  Pipfile.lock
Labels: bot
