Repository thoth-station/build-watcher, pull requests merged in 2020-04, with the labels that each got.

#144 Automatic update of dependency thoth-common from 0.12.4 to 0.12.5
  Pipfile.lock
Labels: bot, size/S

#145 Automatic update of dependency thoth-common from 0.12.5 to 0.12.6
  Pipfile.lock
Labels: bot, size/XS

#146 Automatic update of dependency thamos from 0.9.1 to 0.9.2
  Pipfile.lock
Labels: bot, size/S

#147 Remove latest version restriction from .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#148 Automatic update of dependency thoth-common from 0.12.6 to 0.12.7
  Pipfile.lock
Labels: bot, size/S

#149 Automatic update of dependency thoth-common from 0.12.7 to 0.12.9
  Pipfile.lock
Labels: bot, size/S

#150 Automatic update of dependency thamos from 0.9.2 to 0.9.3
  Pipfile.lock
Labels: bot, size/S

#151 Automatic update of dependency thoth-common from 0.12.9 to 0.12.10
  Pipfile.lock
Labels: bot, size/S

#152 Automatic update of dependency thoth-common from 0.12.10 to 0.13.0
  Pipfile.lock
Labels: bot, size/XS

#153 Automatic update of dependency thoth-common from 0.13.0 to 0.13.1
  Pipfile.lock
Labels: bot, size/XS

#154 Automatic update of dependency click from 7.1.1 to 7.1.2
  Pipfile.lock
Labels: bot, size/XS

#155 Automatic update of dependency thamos from 0.9.3 to 0.9.4
  Pipfile.lock
Labels: bot, size/XS

#156 Automatic update of dependency thamos from 0.9.4 to 0.10.0
  Pipfile.lock
Labels: bot, size/S

#157 Automatic update of dependency thoth-common from 0.13.1 to 0.13.2
  Pipfile.lock
Labels: bot, size/XS
