Repository thoth-station/build-watcher, pull requests merged in 2020-07, with the labels that each got.

#171 Remove latest versions limitation
  .thothTemplate.yaml
Labels: approved, size/XS

#172 Automatic update of dependency thoth-common from 0.13.8 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/M

#173 Automatic update of dependency thamos from 0.10.5 to 0.10.6
  Pipfile.lock
Labels: approved, bot, size/M

#174 support pre-commit
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .pre-commit-config.yaml
  .thoth.yaml
  .zuul.yaml
  README.rst
  app.py
Labels: approved, size/L
