Repository thoth-station/build-watcher, pull requests merged in 2020-01, with the labels that each got.

#92 Happy new year!
  app.py
Labels: approved, size/XS

#93 Flexibility to push images to quay
  app.py
Labels: approved, size/S

#96 Automatic update of dependency pyyaml from 5.2 to 5.3
  Pipfile.lock
Labels: bot, size/M

#94 thoth configmap required for build-watcher
  openshift/configmap-template.yaml
  openshift/deployment-template.yaml
Labels: approved, size/M

#95 updated playbook with required parameters
  playbooks/build-watcher/tasks/main.yaml
  playbooks/deprovision.yaml
  playbooks/provision.yaml
Labels: approved, size/M

#97 Do not run adviser from bc in debug mode
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#98 sa and rolebinding creation separated
  openshift/deployment-template.yaml
  openshift/service-account-template.yaml
  playbooks/build-watcher/tasks/main.yaml
Labels: approved, size/L

#99 setup probe on dc as it uses events
  openshift/deployment-template.yaml
Labels: approved, size/XS

#100 Automatic update of dependency thoth-common from 0.9.22 to 0.9.23
  Pipfile.lock
Labels: bot, size/XS

#101 Push base image to external registry too
  app.py
Labels: approved, size/S

#102 Fixing @ issue in image push to quay
  app.py
Labels: approved, size/XS

#103 Remove redundant if statement
  app.py
Labels: approved, size/XS

#104 Automatic update of dependency thoth-common from 0.9.23 to 0.9.24
  Pipfile.lock
Labels: bot, size/S

#105 Automatic update of dependency thoth-common from 0.9.24 to 0.9.25
  Pipfile.lock
Labels: bot, size/S

#106 Automatic update of dependency thoth-common from 0.9.25 to 0.9.26
  Pipfile.lock
Labels: bot, size/S

#107 Automatic update of dependency thoth-analyzer from 0.1.7 to 0.1.8
  Pipfile.lock
Labels: bot, size/S

#108 Automatic update of dependency thoth-common from 0.9.26 to 0.9.28
  Pipfile.lock
Labels: bot, size/XS

#112 Automatic update of dependency thoth-common from 0.9.28 to 0.9.29
  Pipfile.lock
Labels: bot, size/S

#114 Fixing traceback raise issue with warning
  app.py
Labels: approved, size/XS

#117 Automatic update of dependency thoth-common from 0.9.29 to 0.9.30
  Pipfile.lock
Labels: bot, size/M

#118 Automatic update of dependency thoth-common from 0.9.30 to 0.9.31
  Pipfile.lock
Labels: bot, size/S

#119 Automatic update of dependency thoth-common from 0.9.31 to 0.10.0
  Pipfile.lock
Labels: bot, size/L

#120 Automatic update of dependency thamos from 0.7.7 to 0.8.0
  Pipfile.lock
Labels: bot, size/S

#116 Catch the manifest exception as warning
  app.py
Labels: approved, size/S

#121 Automatic update of dependency thoth-common from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: bot, size/S
