Repository thoth-station/build-watcher, pull requests merged in 2020-02, with the labels that each got.

#122 Automatic update of dependency thoth-common from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: bot, size/XS

#123 Automatic update of dependency thamos from 0.8.0 to 0.8.1
  Pipfile.lock
Labels: bot, size/S

#124 Automatic update of dependency thoth-common from 0.10.2 to 0.10.3
  Pipfile.lock
Labels: bot, size/XS

#125 Automatic update of dependency thoth-common from 0.10.3 to 0.10.4
  Pipfile.lock
Labels: bot, size/XS

#126 Automatic update of dependency thoth-common from 0.10.4 to 0.10.5
  Pipfile.lock
Labels: bot, size/S

#127 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#128 Automatic update of dependency thoth-common from 0.10.5 to 0.10.6
  Pipfile.lock
Labels: bot, size/S

#129 Automatic update of dependency thoth-common from 0.10.6 to 0.10.7
  Pipfile.lock
Labels: bot, size/S

#130 Automatic update of dependency thoth-common from 0.10.7 to 0.10.8
  Pipfile.lock
Labels: bot, size/M

#131 Automatic update of dependency thoth-common from 0.10.8 to 0.10.9
  Pipfile.lock
Labels: bot, size/S
